name: Build

on:
  push:
    branches: ["main", "features/*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pour avoir accès à des variables plus simples comme GITHUB_REF_SLUG_URL
      - name: GitHub Slug Action
        uses: rlespinasse/github-slug-action@3.1.0

      - name: Set variables
        run: |
          echo ${GITHUB_REF_SLUG}
          if [[ "${GITHUB_REF_SLUG}" == features* ]]; then
            echo "DESTINATION_FOLDER=/${GITHUB_REF_SLUG}" >> $GITHUB_ENV
          else
            echo "DESTINATION_FOLDER=/" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build

      - run: echo ${{ github.sha }} > dist/commit

      - name: npm run test:unit
        run: npm run test:unit

      - name: Package build
        run: mkdir target && tar -cvzf target/package.tgz dist

      - name: Upload current build
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          name: ${{ env.GITHUB_REF_SLUG_URL }}
          path: target
          cleanup: true

      - name: Deploy current build
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7.1
        with:
          connection_string: ${{ secrets.DEV_ST_CONNECTION_STRING }}
          container_name: $web
          source_folder: dist/
          destination_folder: ${{ env.DESTINATION_FOLDER }}

      - name: Publication rapports de tests
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7.1
        if: ${{ success() || failure() }}
        with:
          connection_string: ${{ secrets.REPORTS_ST_CONNECTION_STRING }}
          container_name: $web
          source_folder: reports/
          destination_folder: ${{ github.repository }}/${{ env.GITHUB_REF_SLUG_URL }}
