name: Promote to prod

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download latest build from app
        uses: fixpoint/azblob-download-artifact@v3
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          name: app
          path: dist

      - name: Upload current build
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          cleanup: true
          name: prod
          path: dist

      - name: Deploy current build
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7.1
        with:
          connection_string: ${{ secrets.PROD_ST_CONNECTION_STRING }}
          container_name: $web
          source_folder: dist/
