name: Promote to approbation

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 100

      - name: Download latest build from develop
        uses: fixpoint/azblob-download-artifact@v3
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          name: develop
          path: target

      - name: Unpack build
        run: |
          tar -zxvf target/package.tgz
          commit_sha=$(cat dist/commit)
          echo Current commit is: $commit_sha
          echo "COMMIT_SHA=${commit_sha}" >> $GITHUB_ENV

      - name: Merge forward main branch
        run: |
          echo "Fetching last commit of main branch..."
          git fetch origin main:main_tmp --depth=1

          echo "Forwarding main branch..."
          git fetch origin ${{ env.COMMIT_SHA }}:main_tmp

          echo "Pushing changes..."
          git push origin main_tmp:main

      - name: Upload current build
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          cleanup: true
          name: app
          path: target

      - name: Deploy current build
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7.1
        with:
          connection_string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container_name: $web
          source_folder: dist/
