name: Promote to approbation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download latest build from main branch
        uses: fixpoint/azblob-download-artifact@v3
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          name: main
          path: dist

      - name: Upload current build
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          cleanup: true
          name: app
          path: dist

      - name: Deploy current build
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7.1
        with:
          connection_string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container_name: $web
          source_folder: dist/
