name: Promote to prod

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Promote to prod from app
        uses: ./.github/actions/promote
        with:
          src: app
          dest: prod
          dest-connection-string: secrets.PROD_ST_CONNECTION_STRING
