name: Promote to prod

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 5

      - name: Download latest build from app
        uses: fixpoint/azblob-download-artifact@v3
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          name: app
          path: target

      - name: Unpack build
        run: |
          tar -zxvf target/package.tgz
          commit_sha=$(cat dist/commit)
          echo Current commit is: $commit_sha
          echo "COMMIT_SHA=${commit_sha}" >> $GITHUB_ENV

      - name: Upload current build
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          cleanup: true
          name: prod
          path: target

      - name: Deploy current build
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7.1
        with:
          connection_string: ${{ secrets.PROD_ST_CONNECTION_STRING }}
          container_name: $web
          source_folder: dist/

      - name: Create tag
        run: |
          tagName=v`date +"%Y-%m-%d-%H-%M-%S"`
          git tag -m "Release to prod" -f $tagName ${{ env.COMMIT_SHA }}
          git push origin $tagName
