name: Promote to prod

on:
  workflow_dispatch:

jobs:
  promote-to-prod:
    runs-on: ubuntu-latest

    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10

      - name: Compute tag name
        run: |
          TAG_NAME=v`TZ=America/New_York date +"%Y-%m-%d-%H-%M-%S"`
          echo TAG_NAME=$TAG_NAME >> $GITHUB_ENV

      - name: Download latest build from app
        uses: fixpoint/azblob-download-artifact@v3
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          name: app
          path: target

      - name: Unpack build
        run: |
          tar -zxvf target/package.tgz
          commit_sha=$(cat dist/commit)
          echo Current commit is: $commit_sha
          echo "COMMIT_SHA=${commit_sha}" >> $GITHUB_ENV

      - name: Upload current build
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.APP_ST_CONNECTION_STRING }}
          container: artifacts
          cleanup: true
          name: ${{ env.TAG_NAME }}
          path: target

      - name: Create tag
        run: |
          git config user.email "github@ulaval.ca"
          git config user.name "Github actions"
          git tag -m "Release to prod" -f ${{ env.TAG_NAME }} ${{ env.COMMIT_SHA }}
          git push origin ${{ env.TAG_NAME }}

      - name: Deploy application
        uses: ulaval/azure-blob-copy-action@main
        with:
          action: upload
          connection_string: ${{ secrets.ST_CONNECTION_STRING }}
          container_name: $web
          local_directory: dist
          http_headers: |
            - glob: "**/*.????????.*"
              headers:
                Cache-Control: public, max-age=604800, immutable

            - glob: "**/*"
              headers:
                Cache-Control: public, max-age=120, s-maxage=180, proxy-revalidate
